#!/bin/bash

ARGS=$@

exec java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -classpath /home/bryan/.sbt/boot/scala-2.10.0/lib/scala-library.jar:/home/bryan/.ivy2/cache/org.parboiled/parboiled-scala_2.10/bundles/parboiled-scala_2.10-1.1.5.jar:/home/bryan/.ivy2/cache/org.parboiled/parboiled-core/bundles/parboiled-core-1.1.5.jar:/home/bryan/.ivy2/cache/jline/jline/jars/jline-2.10.jar:/home/bryan/.ivy2/cache/org.scalaz/scalaz-core_2.10/bundles/scalaz-core_2.10-7.0.2.jar:./target/scala-2.10/classes TerminalMain debug
